serial:
  device: /dev/ttyUSB0
http:
  listen-address: ":8081"
namespace: p1
metrics:
  "1-0:1.8.1":
      name: electricity_delivered_to_client_kwh
      description: Meter Reading electricity delivered to client in 0,001 kWh
      type: counter
      unit: kWh
      labels:
        tariff: 1
  "1-0:1.8.2":
      name: electricity_delivered_to_client_kwh
      description: Meter Reading electricity delivered to client in 0,001 kWh
      type: counter
      unit: kWh
      labels:
        tariff: 2
  "1-0:2.8.1":
      name: electricity_delivered_by_client_kwh
      description: Meter Reading electricity delivered by client in 0,001 kWh
      type: counter
      unit: kWh
      labels:
        tariff: 1
  "1-0:2.8.2":
      name: electricity_delivered_by_client_kwh
      description: Meter Reading electricity delivered by client in 0,001 kWh
      type: counter
      unit: kWh
      labels:
        tariff: 2
  "1-0:1.7.0":
      name: actual_electricity_delivered_kw
      description: Actual electricity power delivered (+P) in 0,001 kW
      type: gauge
      unit: kW
  "1-0:2.7.0":
      name: actual_electricity_received_kw
      description: Actual electricity power received (-P) in 0,001 kW
      type: gauge
      unit: kW
  "0-0:96.14.0":
      name: tariff_indicator_electricity
      description: Tariff indicator electricity
      type: gauge
  "0-0:17.0.0":
      name: actual_threshold_electricity_kw
      description: Actual threshold electricity
      type: gauge
      unit: kW
  "0-0:96.7.21":
      name: power_failures_total
      description: Number of power failures in any phase
      type: counter
  "0-0:96.7.9":
      name: long_power_failures_total
      description: Number of long power failures in any phase
      type: counter
  "1-0:32.32.0":
      name: voltage_sags
      description: Number of voltage sags
      type: counter
      labels:
        phase: L1
  "1-0:52.32.0":
      name: voltage_sags
      description: Number of voltage sags
      type: counter
      labels:
        phase: L2
  "1-0:72.32.0":
      name: voltage_sags
      description: Number of voltage sags
      type: counter
      labels:
        phase: L3
  "1-0:32.36.0":
      name: voltage_swells
      description: Number of voltage swells
      type: counter
      labels:
        phase: L1
  "1-0:52.36.0":
      name: voltage_swells
      description: Number of voltage swells
      type: counter
      labels:
        phase: L2
  "1-0:72.36.0":
      name: voltage_swells
      description: Number of voltage swells
      type: counter
      labels:
        phase: L3
  "1-0:31.7.0":
      name: current_a
      description: Instantaneous current in A resolution
      type: gauge
      unit: A
      labels:
        phase: L1
  "1-0:51.7.0":
      name: current_a
      description: Instantaneous current in A resolution
      type: gauge
      unit: A
      labels:
        phase: L2
  "1-0:71.7.0":
      name: current_a
      description: Instantaneous current in A resolution
      type: gauge
      unit: A
      labels:
        phase: L3
  "1-0:32.7.0":
      name: voltage_v
      description: Instantaneous voltage in V resolution
      type: gauge
      unit: V
      labels:
        phase: L1
  "1-0:52.7.0":
      name: voltage_v
      description: Instantaneous voltage in V resolution
      type: gauge
      unit: V
      labels:
        phase: L2
  "1-0:72.7.0":
      name: voltage_v
      description: Instantaneous voltage in V resolution
      type: gauge
      unit: V
      labels:
        phase: L3
"1-0:21.7.0":
      name: active_power_delivered_kw
      description: Instantaneous active power (+P) in W resolution
      type: gauge
      unit: W
      labels:
        phase: L1
  "1-0:41.7.0":
      name: active_power_delivered_kw
      description: Instantaneous active power (+P) in W resolution
      type: gauge
      unit: W
      labels:
        phase: L2
  "1-0:61.7.0":
      name: active_power_delivered_kw
      description: Instantaneous active power (+P) in W resolution
      type: gauge
      unit: W
      labels:
        phase: L3
  "1-0:22.7.0":
      name: active_power_received_kw
      description: Instantaneous active power (-P) in W resolution
      type: gauge
      unit: W
      labels:
        phase: L1
  "1-0:42.7.0":
      name: active_power_received_kw
      description: Instantaneous active power (-P) in W resolution
      type: gauge
      unit: W
      labels:
        phase: L2
  "1-0:62.7.0":
      name: active_power_received_kw
      description: Instantaneous active power (-P) in W resolution
      type: gauge
      unit: W
      labels:
        phase: L3
  "0-1:24.2.3":
      name: gas_m3
      description: Gas meter reading in m3
      type: counter
      unit: m3
